apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: cave-enki-frontend
  name: cave-enki-frontend
  namespace: cave-enki
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: cave-enki-frontend
  type: LoadBalancer
  loadBalancerIP: "35.187.163.19"
status:
  loadBalancer: {}
